language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g bower
  - bower install
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'angular-gs-stereotype' ]; then cd .. && eval "mv $currentfolder angular-gs-stereotype" && cd angular-gs-stereotype; fi
